name: test-ui
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - '.changelog/**'
      - '.tours/**'
      - 'contributing/**'
      - 'demo/**'
      - 'dev/**'
      - 'e2e/**'
      - 'integrations/**'
      - 'pkg/**'
      - 'scripts/**'
      - 'terraform/**'
      - 'website/**'
  push:
    branches:
      - main
      - release/**
      - test-ui
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - '.changelog/**'
      - '.tours/**'
      - 'contributing/**'
      - 'demo/**'
      - 'dev/**'
      - 'e2e/**'
      - 'integrations/**'
      - 'pkg/**'
      - 'scripts/**'
      - 'terraform/**'
      - 'website/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: yarn install
        run: cd ui && yarn install --frozen-lockfile
      - name: lint:js
        run: cd ui && yarn run lint:js
      - name: lint:hbs
        run: cd ui && yarn run lint:hbs
  tests:
    needs:
      - lint
    strategy:
      matrix:
        partition: [1, 2, 3, 4]
        split: [4]
    uses: ./.github/workflows/_ember-exam.yml
    with:
      partition: ${{ matrix.partition }}
      split: ${{ matrix.split }}
  finalize:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - tests
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: yarn install
        run: cd ui && yarn install --frozen-lockfile
      - name: finalize
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: cd ui && yarn percy -- build:finalize
permissions:
  contents: read
